### ISSUE TITLE
ab might treat some requests as failed because of response length difference

### ISSUE THREAD

**Issue by ogvolkov** [vasilevsky/Sync2AsyncPerf#1]
API returns customer id, and it can vary in length when reaching power of ten boundary (9999/10000), causing ab treat it as a false error.

We need to add -l flag to the sample script to avoid this, see http://stackoverflow.com/a/7731204/76176

**Comment by vasilevsky** [comment]
This could be a solution but I have a suspicion that length may be an indicator of malfunctioning.
So I would rather propose to return id with several digits padding e.g 00000001356 or rather set DB identity to bigger number e.g. 100 000 000.
What do you think?

**Comment by vasilevsky** [comment]
OK. For now I went with following solution: introduced IdentityContent which does 100 000 000 + id and outputs to response.
After I performed tests found that -length errors still appear. So my suspicion was correct.

**Comment by ogvolkov** [comment]
It would be much more clear to include the dynamic flag, because well the response IS dynamic.
